spring.datasource.url=jdbc:mysql://localhost:3306/dining_reviews
spring.datasource.username=*****
spring.datasource.password=*****
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#used to display sql command on the console
spring.jpa.show-sql=true

# which dialect is used (changed)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# configures what should be done to the db
spring.jpa.hibernate.ddl-auto=update
# configures if JSON should include null properties
spring.jackson.default-property-inclusion=non-null
# whether to include response status message
server.error.include-message=always
# to enable fast loading of changes
spring.devtools.restart.enabled=true

# We need Hibernate to create our tables before inserting the data
spring.jpa.defer-datasource-initialization=true
